require("@rails/ujs").start()
require("turbolinks").start()
// require("@rails/activestorage").start()
// require("channels")

require("./front/dogs")
require("./front/home")
require("./front/favorites")
require("./front/header")
require("./front/menu")
require("./front/profiles")
require("./front/gallery")
